name: 'OSS Gate Issue Cleaner'
description: 'Cleaning issues of OSS Gate Workshop repository'
inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to making API requests
    required: true
    default: ${{ github.token }}
  DOORKEEPER_GROUP:
    description: Group name of doorkeeper community
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'lib/main.js'
